### ISSUE TITLE
Error when I press a key in an xml file

### ISSUE THREAD

**Issue by NewKrok** [DoclerLabs/hexDevelop#20]
I tried to write some new entry into an xml file, but I always got an error when I pressed a key. As I know I use the latest hexmachina.

here is the error:

System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.InternalSubStringWithChecks(Int32 startIndex, Int32 length, Boolean fAlwaysCopy)
   at DSLCompletion.DSLComplete.FindSelection(Check isAllowedChar, Boolean checkRight)
   at DSLCompletion.DSLComplete.GetCompletion()
   at DSLCompletion.PluginMain.OnChar(ScintillaControl sci, Int32 value)
   at PluginCore.Controls.UITools.CharAddedHandler.Invoke(ScintillaControl sender, Int32 value)
   at PluginCore.Controls.UITools.SendChar(ScintillaControl sci, Int32 value)
   at PluginCore.Controls.UITools.OnChar(ScintillaControl sci, Int32 value)
   at ScintillaNet.CharAddedHandler.Invoke(ScintillaControl sender, Int32 ch)
   at ScintillaNet.ScintillaControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by chipshort** [comment]
That's strange. I cannot reproduce it, but I made some changes.
Does it happen with every xml file or was it a specific file? Can you send me an example?
